export const servicesMock = [
  {
    img: "https://img.freepik.com/fotos-premium/interior-de-casa-de-luxo-com-bela-sala-de-estar-quarto_528398-415.jpg?w=740",
    title: "Móveis Sob Medida",
    subtitle:
      "Pinturas, Marcenaria, Carpintaria, Pedreiro, Ladrilheiro, Vidraceiro",
    slug: "eletrica",
    icon: "",
    services: [
      "Quadro de distribuição (instalação completa desde o início)",
      "Disjuntores",
      "Tomadas",
      "Interruptores",
      "IDR / DR",
      "Dimer",
      "Campainha",
      "Chuveiro (Instalação e Troca), troca de resistência, fiação.",
      "Lâmpada, luminária, croica, LED, barra de LED, lustres, arandelas, abajur.",
      "Fiação (adequação e troca)",
      "Fiação para TV/rede",
      "Fechadura eletrônica",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2015/12/07/10/55/electric-1080584_1280.jpg",
      "https://www.picclickimg.com/6zkAAOSwN8plZOAl/Aigostar-Lampada-Da-Soffitto-LED-Bagno-18W-Equivalente.webp",
    ],
  },
  {
    img: "https://cdn.pixabay.com/photo/2016/12/30/08/00/kitchen-1940177_1280.jpg",
    title: "Luxo e Requinte",
    subtitle: "Elétrica em Geral do Lar e de Empresas!",
    slug: "hidraulica",
    icon: "",
    services: [
      "Registro (Instalação, Manutenção, Vazamento, Troca)",
      "Chuveiro - instalação",
      "Pia/lavatório (troca de válvula, sifão, vedação com.silicone ou PU, tira vazamento)",
      "Torneira (instalação, troca de reparo, tira vazamento)",
      "Instalação de filtro e ou purificador, máquinas de lavar roupa, máquina de lavar louça)",
      "Instalação hidráulica desde o início",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2018/08/10/18/03/bad-3597350_1280.jpg",
      "https://eletricista24hs.com.br/wp-content/uploads/2023/02/Instalacao-de-chuveiro.png",
      "https://blog.casadastorneiras.com.br/wp-content/uploads/2022/02/torneira-vazando-thumb.jpg",
    ],
  },
  {
    img: "https://cdn.pixabay.com/photo/2016/12/30/07/59/kitchen-1940175_1280.jpg",
    title: "Materiais de Primeira",
    subtitle:
      "Cortinas, Persianas, Corrimãos, Cantoneiras, Quadros, Rodapés, Fechadura eletrônica, Lustres, Etc",
    slug: "esgoto",
    icon: "",
    services: [
      "Instalação de vaso sanitário",
      "Instalação de caixa de descarga",
      "Manutenção e reparos em caixa acoplada",
      "Limpeza de ralos sifão",
      "Desentupimento",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2017/02/24/12/24/bathroom-2094733_1280.jpg",
      "https://sorodesentupidora.com.br/wp-content/uploads/2019/05/como-funciona-a-instalacao-de-vasos-sanitarios-min.png",
      "https://www.cleanipedia.com/images/00d1hxgfwfa6/6AThNqVUK9bQOT3ypnF53s/a6b9084412b78b78c0360c90b8ccb1b6/Q19waWFfZGVfQ19waWFfZGVfQ0xQXy1fTm92ZW1icm8wMV9fMTdfLmpwZw/1200w/como-limpar-ralo-de-banheiro.jpg",
    ],
  },
  {
    img: "https://cdn.pixabay.com/photo/2016/04/18/08/50/kitchen-1336160_1280.jpg",
    title: "Orçamento Gratuito",
    subtitle: "Montagem e desmontagem de móveis para o Lar e para empresas.",
    slug: "servicos-diversos",
    icon: "",
    services: [
      "Instalação de coifa/depurador",
      "Instalação de varal",
      "Desentupimento de fogão",
      "Limpeza de exaustor de banheiro",
      "Instalação de TV (parede, teto, painel)",
      "Instalação de corrimãos",
      "Instalação de cortinas/persianas",
      "Instalação de barra de apoio ou sustentação",
      "Instalação de quadros, relógios, santuário, cascatas,. cantoneiras",
    ],
    images: [
      "https://cdn.pixabay.com/photo/2016/11/19/13/06/bed-1839183_1280.jpg",
      "https://s2-techtudo.glbimg.com/tC9uKY7Y26eQlRuT7MiYIs2U3Uo=/0x0:1000x764/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2019/5/a/VPsdJcQBAVfMVqxgOdag/0.veja-o-que-voce-precisa-saber-antes-de-comprar-e-instalar-um-suporte-de-parede-para-tv.jpg",
    ],
  },
];
